GET http://localhost:5000/mitra

###
POST http://localhost:5000/mitra
Content-Type: application/json

{
    "nama_coffeeshop": "Stako Kopi",
    "alamat": "Dekat kost anggur",
    "pj": "Husnan maulana",
    "jabatan": "Direktur",
    "cp_pj": "081122334455",
    "jml_tmpt_sampah": 0
}

###
GET http://localhost:5000/mitra/1

###
PUT  http://localhost:5000/mitra/1
Content-Type: application/json

{
    "nama_coffeeshop": "Fore Pakuwon",
    "alamat": "Pakuwon mall Jogja",
    "pj": "Harry Styles",
    "jabatan": "Kepala OB",
    "cp_pj": "081234567890",
    "jml_tmpt_sampah": 1
}

###
DELETE http://localhost:5000/mitra/1